# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f13d64fe786c34613e45f320d0aac3f2d561ac44f215a26768966da300eeaedb1e789d0bd138c7a164abbb65f14d33a9f559e0629c1b4c9dbd001985bd92c666

test:
  secret_key_base: d304f3e679d7cb9b2a77b9e9f956c7e22759029e80a86cbc8e37f298ac716477d7fa46a4b3cb32203cc6f031083a574c2f6a8c07490358fc4295c50d586c0dce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
